<?php

/**
 * Implements hook_theme().
 */
function nurani_osis_field_picker_theme($existing, $type, $theme, $path) {
  return array(
    'nurani_osis_field_picker_dialog' => array(
      'variables' => array('element' => NULL),
      'template' => 'nurani-osis-field-picker-dialog',
    ),
  );
}

/**
 * Implements hook_preprocess_osis_field().
 */
function nurani_osis_field_picker_preprocess_osis_field(&$vars) {
  $path = drupal_get_path('module', 'nurani_osis_field_picker');

  $vars['element']['osisID']['#attached']['css'][] = $path . '/css/picker.css';
  $vars['element']['osisID']['#attached']['js'][]  = $path . '/js/picker.js';

  $vars['element']['osisID']['#suffix'] = theme('nurani_osis_field_picker_dialog', $vars['element']);
}

/**
 * Implements hook_preprocess_nurani_osis_field_picker_dialog().
 */
function nurani_osis_field_picker_preprocess_nurani_osis_field_picker_dialog(&$vars) {
  drupal_add_library('system', 'ui.dialog');

  $vars['osisID'] = $vars['element']['osisID']['#default_value'];
  $vars['osisIDWork'] = $vars['element']['osisIDWork']['#default_value'];
}