<?php

/**
 * Implementation of hook_notifications().
 */
function nurani_notifications_notifications($op, &$arg0, $arg1, $arg2) {
  if ($op == 'event queued') {
    $uids = array();

    if ($arg0->type == 'node') { // node create/update notification
      if ($arg0->node->type == 'discussion') {
        // Only notify users who are invited to the discussion.
        $uids[] = $arg0->node->uid;
        foreach (array('field_moderators', 'field_translators', 'field_scholars') as $field) {
          if (!empty($arg0->node->{$field})) foreach ($arg0->node->$field as $item) {
            $uids[] = $item['uid'];
          }
        }
      }
    }

    // Only notify users who have signed the agreement.
    $result = db_query("SELECT uid FROM {agreement} WHERE agreed=1 AND uid IN (" . db_placeholders($uids, 'int') . ")", $uids);
    $uids = array();
    while ($agreement = db_fetch_object($result)) {
      $uids[] = $agreement->uid;
    }

    // Remove users not included above from the notification.
    db_query("DELETE FROM {notifications_queue} WHERE eid=%d AND uid NOT IN (" . db_placeholders($uids, 'int') . ")", array_merge((array) $arg0->eid, $uids));
  }
}

