<?php

/**
 * Implementation of hook_nodeapi().
 */
function nurani_glossary_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // If someone highlights a text, and redirected to term add page.
  if ($op == 'prepare' && $node->type == 'term' && !$node->nid) {
    if (isset($_GET['title']))
      $node->title = strtolower($_GET['title']);
    if (isset($_GET['language']))
      $node->language = $_GET['language'];
  }
}

/**
 * Template preprocessor for theme('node').
 */
function nurani_glossary_preprocess_node(&$vars) {
  if (in_array($vars['node']->type, array('discussion', 'text')) && user_access('create term content')) {
    static $once = FALSE;
    if (!$once) {
      $once = TRUE;
      $path = drupal_get_path('module', 'nurani_glossary');
      drupal_add_js(array('nurani_glossary' => array(
        'language' => $vars['node']->language, // pass to new glossary form
        'url' => url('node/add/term'),
      )), 'setting');
      drupal_add_js($path . '/js/jquery.selectlink.js');
      drupal_add_js($path . '/js/nurani_glossary.js');
    }
  }
}

