<?php
/*
 * 
 * @file This is the core ICanLocalize service. This provides the API for other modules
 * to access ICanLocalize services
 */

define ( 'ICL_ICANLOCALIZE_WEB', 'http://www.icanlocalize.com' );

define ( 'ICL_ICANLOCALIZE_LINK', '<a href="http://www.icanlocalize.com">ICanLocalize</a>' );

// help and instructions links
define ( 'ICL_INSTALL_AND_SETUP_GUIDE', 'http://drupal-translation.com/install-and-setup-guide/');
define ( 'ICL_INSTALL_AND_SETUP_GUIDE_LANGUAGES', 'http://drupal-translation.com/install-and-setup-guide/#translation_languages');
define ( 'ICL_PASSWORD_REMINDER', '<a href="https://www.icanlocalize.com/login/password_reminder">https://www.icanlocalize.com/login/password_reminder</a>');
define ( 'ICL_FINANCE_LINK', '/finance');
define ( 'ICL_PRIVATE_TRANSLATORS', '<a href="https://www.icanlocalize.com/private_translators">translators management</a>');
define ( 'ICL_EMAIL_VERIFY_LINK', '<a href="https://www.icanlocalize.com/login/complete_registration/!USER_ID">send that email again</a>.');
define ( 'ICL_SUPPORT_LINK', '<a href="https://www.icanlocalize.com/support/new">contact ICanLocalize</a>');
define ( 'ICL_DRUPAL_TRANSLATION_INFO', '<a href="http://www.icanlocalize.com/drupal-translation.html">more info</a>');
define ( 'ICL_COMMENT_NOTE', '<a href=\'http://drupal-translation.com/node/62\'>note</a>');

define ( 'ICL_ACCOUNT_SIGNUP', 'https://www.icanlocalize.com/users/new?utype=Client');
define ( 'ICL_SETUP_INFO', 'http://drupal-translation.com/node/145');
define ( 'ICL_IMAGE_REPLACEMENT_INFO', 'http://drupal-translation.com/node/133');


define ( 'ICL_DRUPAL_PROJECT_KIND', 2);

?>