array(
  array(
    'nid' => '3',
    'type' => 'page',
    'language' => 'en',
    'uid' => '1',
    'status' => '1',
    'created' => '1305843625',
    'changed' => '1305843625',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '3',
    'translate' => '0',
    'vid' => '3',
    'revision_uid' => '1',
    'title' => 'Privacy',
    'body' => 'Nurani.org is designed to allow you to take part in dialogues about your beliefs and opinions, so it is very important that you read and agree to the following terms which relate to how we store personal data that you submit to the platform. The terms form part of the contract that you agree to on registering with this website, but are also here to reassure you that the Cambridge Inter-faith Programme and Meedan, Inc. (the Service Providers) have a strict data policy in place to protect your personal data.
                
                We (The Service Providers) reserve the right to modify the information contained herein at anytime. If we do make changes to our privacy policy that affect your personal data, we will notify You (the Registered User) using the email that you have given us. This site and all information and materials on it are provided to you "as is" without warranty of any kind. Ÿour use of this site, or your provision to us of any personal information constitutes your agreement to these terms; do not use the site or provide information if you do not agree with all of the terms.
                
                Information You Provide
                
                1. Registration
                
                When you register for an account you will be asked to give your name, email address and password.  You can update this information at any time. Only you will be able to see your password. Your email address will be viewable by system administrators representing The Service Providers and moderators granted permission to manage dialogues on Nurani.org by CIP. We will use your email address to communicate important notifications about this privacy policy, requests for disclosure by Third Parties, or other notifications that relate to your use of Nurani.org.   Moderators may use your email address to help manage dialogues on Nurani.org and to warn you if your behaviour is deemed inappropriate.  You can also opt to receive notifications of new content that will be delivered automatically to your email address.
                
                2. Profile Information
                
                When you register for an account you will have the option to build a profile. This profile may include, but is not limited to, information such as your personal names, location, education, professional experience and affiliations. You will be able to edit and remove this information at any time, and to control whether it is viewable publicly or only by other users of Nurani.org. We encourage you to supply this information to help other users learn more about you. We think this will help you to have more productive dialogues with other users.
                
                3. Posting
                
                On Nurani.org you can post three kinds of content: texts, glossary terms, and discussion comments.  We intend for all texts and glossary terms added to Nurani.org to be publicly viewable.  Discussions, however, depend on the privacy settings of the group to which you were invited by a moderator. A discussion on Nurani may have one of three settings: private to the members of the group, viewable by all groups on Nurani, or public on the web. Identification of all contributed content may include, but is not limited to, display of your account name. All content may be retained for restorative, archival, or research purposes by The Service Providers. Editing or deleting content may alter the displayed state of the content, but will not permanently delete the content from the website.
                
                4. Normal Browsing
                
                The Service Providers collect certain information about your browsing habits, including your IP address, URL request, browser type, and date and time of your request. This information is gathered on an aggregate basis only. For example, we track which pages are most popular among visitors as a whole.  We do not track information on which pages an individual user visits. We do not collect any other information without your knowledge and permission.
                
                We analyze traffic to Nurani.org  in various ways, including using a service called Google Analytics. (Google Analytics is subject to the privacy policy of Google, Inc., which you can find at the following url: http://www.google.co.uk/intl/en/privacy/privacy-policy.html) Unless you affirmatively provide additional information, we do not collect or store personally identifiable information such as mailing address, phone number, or social security number.
                Storage
                
                By agreeing to these terms you consent that personal data collected on Nurani.org may be transferred to, and stored at, a destination outside the European Economic Area (“EEA”). It may also be processed by staff operating outside the EEA who work for the Cambridge Inter-faith Programme (CIP) or for Meedan, Inc. By submitting your personal data, you agree to this transfer, storing or processing.
                
                Security
                
                The Service Providers will take all reasonable steps to ensure that your data is treated securely and in accordance with the European Commission’s contractual requirements for the transfer of personal data to processors outside the EU. In order to prevent against accidental or unlawful destruction or accidental loss, alteration, or unauthorised disclosure or access, The Service Providers have put in place strict technical and managerial procedures to safeguard and secure the information processed by Nurani.org.  If you wish to review these measures click here.
                
                
                Disclosure of Information
                
                Available log records, account information, and all data stored on our servers may be accessed by system administrators representing The Service Providers.
                
                In the event that we are required by law (including a court order) to disclose the information you submit, we will provide you with notice that a request for your information has been made so that you may object to the disclosure. We will send this notice by email to the address you have given us.
                
                The Service Providers will take all reasonable measures to notify you in advance of any planned transfer of your personal data to a Third Party or Subprocessor so that you can opt to remove your data from this transfer if you wish. In the unlikely event of unauthorised access to your data, The Service Providers undertake to inform you promptly.
                
                If you have any questions regarding the personal data The Service Providers hold about you, you can contact Meedan’s Data Protection Manager at the following address:
                
                privacy@meedan.net
                
                Meedan, Inc.
                972 Mission Street,
                San Francisco
                California 94310
                USA
                Cookies
                The Service Providers may use session cookies when you visit our website while your browser is open, or while you are logged into Nurani.org. To facilitate registration and login functions, The Service Providers may use cookies to recognise when you return to the website. If you do not logout of your account, these cookies keep track of your username and password so that you do not have to resubmit the information to log into your account. If others will be using your computer, you should log out of your account so that your login information is cleared.
                
                
                These Terms are licensed under CC http://www.citmedialaw.org/) 
                ',
    'teaser' => 'Nurani.org is designed to allow you to take part in dialogues about your beliefs and opinions, so it is very important that you read and agree to the following terms which relate to how we store personal data that you submit to the platform. The terms form part of the contract that you agree to on registering with this website, but are also here to reassure you that the Cambridge Inter-faith Programme and Meedan, Inc. (the Service Providers) have a strict data policy in place to protect your personal data.
                
',
    'log' => '',
    'revision_timestamp' => '1305843625',
    'format' => '1',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:0:{}',
    'path' => 'content/privacy',
    'has_body' => '1',
    'comment_type' => '',
    'last_comment_timestamp' => '1305843625',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'uuid' => '5c239d2c-7ce4-11e0-9ecb-001ec21e5234',
    'revision_uuid' => '5c23da8a-7ce4-11e0-9ecb-001ec21e5234',
    'menu' => array(
      'link_title' => 'Privacy',
      'mlid' => 0,
      'plid' => '0',
      'menu_name' => 'secondary-links',
      'weight' => '3',
      'options' => array(),
      'module' => 'menu',
      'expanded' => '0',
      'hidden' => '0',
      'has_children' => '0',
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
