array(
  array(
    'nid' => '5',
    'type' => 'page',
    'language' => 'ar',
    'uid' => '1',
    'status' => '1',
    'created' => '1305843625',
    'changed' => '1305843625',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '1',
    'translate' => '0',
    'vid' => '5',
    'revision_uid' => '1',
    'title' => 'About Nurani.org',
    'body' => '<a href="http://nurani.org">Nurani.org</a> is a platform for dialogue between Muslims and Christians in two languages - Arabic and English.
                
                The product of a collaboration between the Cambridge Inter-faith Programme at the University of Cambridge, the nonprofit technology company Meedan, the Coexist Foundation, and a consortium of universities and research centres, it allows scholars from the two faith traditions to share and study their scriptures together.
                
                <a href="http://nurani.org">Nurani.org</a> specifically aims to:
                
                <ul> <li>* enable rich and fruitful discussion of scriptural texts between Muslims and Christians;</li>
                       <li>* facilitate deeper understanding of the lived traditions and beliefs of Islam and Christianity;<li>
                       <li>* build trust and friendship between Christian and Muslim participants; and</li>
                       <li>* develop new research methods for collaboratively studying texts across languages.</li> </ul>
                 
                <br></br>
                Participating in <a href="http://nurani.org">Nurani.org</a> is initially by invitation only, as we are seeking to create a context in which high-quality, well moderated and safe inter-faith discussion can take place between scholars and civic groups.  In the longer term we envisage creating opportunities for dialogues involving the wider public.  To request further information or an invitation to the platform, email info[at]meedan.net or tweet to <a href="http://twitter.com/meedan">@Meedan</a> on Twitter.
                
                <strong>Seeking deeper understanding</strong>
                
                The aim of discussion on <a href="http://nurani.org">Nurani.org</a> is not to secure agreement, but to secure deeper understanding.
                
                Participants from two faiths, Christianity and Islam, meet here to discuss short texts from our respective scriptures – the Bible and the Qur’an. We do this in three ways:
                
                1.     We seek a deeper understanding of the ‘plain sense’ of the texts in front of us.  Do these texts appear to make sense on an initial reading, to a group of readers some of whom are unfamiliar with them?  Do any of us find anything surprising, confusing, intriguing, difficult or upsetting about them?
                
                2.     We seek a deeper understanding of the each other’s traditions.  So a Christian seeks to understand how the Muslims in the group read this Qur’anic text, and a Muslim participant seeks to understand how the Christians read the Biblical text.  We don’t try to speak authoritatively for the whole religious or scholarly tradition of our faith, but simply for ourselves as participants in one of the traditions.  How does each of us, with the formation in our faith that we have had, read this text?  Do the others in the group find anything surprising, confusing, intriguing, difficult or upsetting about our ways of reading it?
                
                3.     We seek a deeper understanding of our own traditions.  When, for instance, a Christian reads a Biblical text in the company of Muslims who ask questions about the text and his or her reading of it, and who suggest other ways in which it seems to them that the text could be read, he or she is driven to look at the text and her reading of it again, with fresh eyes.  And when a Muslim reads a Qur’anic text in the company of Christians who ask questions and suggest other ways of reading, he or she too is driven to look at that text with fresh eyes.  Reading in such diverse company drives understanding deeper.
                
                These are not three separate steps, nor do they involve three separate kinds of discussion.  Rather, these kinds of deeper understanding emerge quite naturally, as the participants discuss the texts in front of them.
                
                
                <strong>Translation</strong>
                
                <a href="http://nurani.org">Nurani.org</a> is designed to be entirely bi-lingual.  Every piece of text will be translated between two languages - Arabic and English - as it is published.  This is made possible by a team of professional translators with religious knowledge working with the translation tools built into the platform.  Currently though we are testing monolingual discussions.
                
                <strong><a href="http://nurani.org/overview">Discussions</a></strong>
                
                On <a href="http://nurani.org">Nurani.org</a>, we bring Christian and Muslim scholars together in small groups to discuss extracts from our sacred or authoritative texts together. A moderator will begin the discussion by inviting you to read selected scriptural extracts and an initial comment that he or she has written. You can then discuss what you have read with the other scholars in the discussion. Learn more about how we moderate discussions on the <a href="http://nurani.org/content/guidance">Guidance page</a>.
                
                <strong><a href="http://nurani.org/texts">Texts</a></strong>
                
                <a href="http://nurani.org/texts">Nurani.org</a> is a place for dialogue about the scriptures that lie at the heart of our religious traditions. These texts have been endlessly fruitful in shaping the thought and practice of each of our traditions, and in our experience they make for the most fruitful meeting point for inter-faith discussion. In most cases, for the Biblical passages we will use the New Revised Standard Version in English at http://bible.oremus.org/ and Biblica http://www.biblica.com/bibles/arabic/ in Arabic. For the Qur’anic passages we will use http://tanzil.net/ in Arabic and the Arthur J. Arberry translation in English.
                
                <strong><a href="http://nurani.org/glossary">Glossary</a></strong>
                
                The <a href="http://nurani.org/glossary">Nurani.org Glossary</a> allows you to log important words and phrases that appear in your scriptures so that discussants from other faiths can better understand the important concepts in your tradition. Each entry in the glossary is called a <em>Term</em> and allows you to add one or multiple translations (English or Arabic), contextual tags, and explanatory annotations.  Each term will also show you where it has appeared on <a href="http://nurani.org">Nurani.org</a>, providing a dynamic concordance of references and linkages between the textual traditions of the two faiths.
                
                <strong>Licenses</strong>
                
                The entire set of resources and tools developed in this project, including the published discussions, the translations, the glossary and the platform itself, is available for re-use under open source license.  The discussion and glossary content is available for re-use under the <a href="http://creativecommons.org/licenses/by-nc/3.0/">Creative Commons Attribution-NonCommercial 3.0 License</a>.  The platform is available for re-use under the GNU General Public License version 2 (GPLv2).
                
                <strong>Partners</strong>
                
                The Inter-faith Platform Project is a collaboration between a number of the world’s leading institutions for faith research, led by the <a href="http://www.interfaith.cam.ac.uk/">Cambridge Inter-faith Programme</a> (CIP), a program of the Faculty of Divinity at the University of Cambridge, UK, and <a href="http://blog.meedan.net">Meedan</a>, a social technology nonprofit based in San Francisco.
                
                CIP is a flagship project of the University of Cambridge 800th Anniversary Campaign, offering a distinctive scholarly approach to furthering understanding across the Abrahamic traditions with a strong emphasis on collaboration and translation. It is taking the lead in building the network of partner institutions using this platform, initiating and moderating dialogues, and creating scholarly resources. Learn more here.
                
                This platform was built by Meedan, a leading charitable provider of advanced technologies for dialogue and cross-language encounter, with expertise in cross-language interaction design and system design for Arabic-English translation on the web. Learn more here.
                
                Thank you for visiting this website today. Find out how you can contribute by emailing info[at]meedan.net or tweeting <a href="http://twitter.com/meedan">@Meedan</a> on Twitter.',
    'teaser' => '<a href="http://nurani.org">Nurani.org</a> is a platform for dialogue between Muslims and Christians in two languages - Arabic and English.
                
                The product of a collaboration between the Cambridge Inter-faith Programme at the University of Cambridge, the nonprofit technology company Meedan, the Coexist Foundation, and a consortium of universities and research centres, it allows scholars from the two faith traditions to share and study their scriptures together.
                
                <a href="http://nurani.org">Nurani.org</a> specifically aims to:
                
',
    'log' => '',
    'revision_timestamp' => '1305843625',
    'format' => '2',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:0:{}',
    'path' => 'content/about-nuraniorg',
    'has_body' => '1',
    'comment_type' => '',
    'last_comment_timestamp' => '1305843625',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'menu' => array(
      'link_title' => 'About Nurani.org',
      'mlid' => 0,
      'plid' => '0',
      'menu_name' => 'secondary-links',
      'weight' => '0',
      'options' => array(),
      'module' => 'menu',
      'expanded' => '0',
      'hidden' => '0',
      'has_children' => '0',
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
