array(
  array(
    'nid' => '6',
    'type' => 'page',
    'language' => 'ar',
    'uid' => '1',
    'status' => '1',
    'created' => '1305843625',
    'changed' => '1305843625',
    'comment' => '0',
    'promote' => '0',
    'moderate' => '0',
    'sticky' => '0',
    'tnid' => '2',
    'translate' => '0',
    'vid' => '6',
    'revision_uid' => '1',
    'title' => 'Guidance',
    'body' => '<strong>Ground rules for discussion</strong>
                
                There are some ground rules to keep in mind, which can help the process work.
                
                The first and most important ground rule is stick to the texts.  It is our experience that these discussions are much more fruitful if the discussion remains focused on the scriptural texts and on the ways in which they can be read – rather than spiralling off to become a general discussion of Islam and Christianity.
                
                The second ground rule is give space to others’ readings.  Even if you have very firm, clear and well-grounded ideas about how a particular text should be read (perhaps it is just obvious to you what this text means, or you know other scriptural texts that help interpret this one, or you know authoritative commentaries on the text from your tradition) don’t simply impose that reading on the group.  The discussion will work best if the other participants are able to hear about the way you believe the text should be read whilst exploring the text, and other possible ways of reading it, for themselves.  That may sometimes mean that you have to sit back for a while, and let a discussion continue that you believe to be mistaken – before finding a way gently to explain to people how and why you read the text the way you do.
                
                The third ground rule is be playful.  This is not an instruction to be frivolous or trivial, or to show disrespect to the group or to the texts.  It is simply that we have found that discussions work best when the participants feel able to make suggestions about how to read the text, even if they are newcomers to it, and don’t yet know whether their suggestions really make sense.  And discussions work best when the participants feel able to ask questions, even if they suspect that the answers might be obvious to other members of the group.
                
                
                <strong>Asking questions</strong>
                
                There’s no fixed recipe for a scriptural discussion on Nurani, but a discussion might start off with simple questions for clarification ­– What does this word mean?  Is this text part of a longer narrative?  Who is speaking in this verse?
                
                The discussion might then begin to move on to questions about how this text is read – how Biblical texts are read by the Christians present, and Qur’anic texts by the Muslims.  So, would you normally read this text as a promise?  How were you taught that this command should be put into practice?  What sort of things have you heard preachers say about this text?  Does this text really get used at marriage ceremonies?
                
                As the participants get into the rhythm of their discussion, the questions might begin to change.  Couldn’t you read it this way?  What if you take this not as a promise but as a threat?  Would it mean something different if you assumed it was addressed to someone who was already a believer?
                
                
                <strong>The role of the moderators</strong>
                
                The moderators are there to help keep the discussion going. 
                
                They initiate the discussion with a first response to the scriptures, proposing some questions and themes that the group might like to discuss.
                
                They are there to encourage the members of the group to join in, if there’s a lull in the talking.
                
                They are there to decide, in consultation with the group, when it is time to move on from one text to another.
                
                They are there to nudge the discussion gently back to the text, if it looks like it is circling away somewhere else.
                
                They are there, if necessary, to send a quiet email to someone who is dominating the discussion too much.
                
                
                <strong>How moderators are selected</strong>
                
                Moderators are carefully selected by CIP staff. Moderators are likely experienced scholars with solid reputations and good experience of convening inter-faith dialogue. CIP will train and support moderators to be able to initiate and engage dialogues on nurani.org for the best results. If you think you would make a good moderator, please contact us here.
                
                <strong>The role of translators</strong>
                
                Nurani.org allows scholars from two faiths, Christianity and Islam, to meet and discuss short texts from their respective scriptures – the Bible and the Qur’an.  Each discussion comprises a collection of scriptural passages, a long-form response from the moderator, and a series of short-form responses from scholars.
                
                When you are invited to translate a discussion, you will receive an email allowing you to review it. Each discussion should include at least one translator who is comfortable translating into Arabic and one translator who is comfortable translating into English, so you only need to focus on the original content that you can translate.
                
                You do not need to translate the scriptures.  In most cases, for the Biblical passages we will use the New Revised Standard Version in English at http://bible.oremus.org/ and Biblica http://www.biblica.com/bibles/arabic/ in Arabic. For the Qur’anic passages we will use http://tanzil.net/ in Arabic and the Arthur J. Arberry translation in English.  But everything else will need to be translated by you and the other translators with access to the discussion. Every time a new response is added by a scholar, or if the original discussion content is changed in any way, you will receive an email notification.
                
                You will also receive an email every time a new term is added to the glossary.  A glossary term is a word or phrase that falls within one part of speech. Glossary term pages allow you to add one or more translations of that term, each with its own ‘context’ tag. A context tag allows you to alert other translators that they should use this term in a particular context.  You can also add explanations of the term and its translations, as can scholars.  The glossary page also functions as a concordance, listing citations of the term across the platform.
                
                Speed of translation is important, but more important still is accuracy. If you are not comfortable translating something, please check with someone else. Remember, all translations on Nurani.org can be edited, so do not feel undermined if your translations are updated by moderators; Nurani.org is designed for collaboration, so making improvements to translations is to be encouraged. 
                ',
    'teaser' => '<strong>Ground rules for discussion</strong>
                
                There are some ground rules to keep in mind, which can help the process work.
                
                The first and most important ground rule is stick to the texts.  It is our experience that these discussions are much more fruitful if the discussion remains focused on the scriptural texts and on the ways in which they can be read – rather than spiralling off to become a general discussion of Islam and Christianity.
                
',
    'log' => '',
    'revision_timestamp' => '1305843625',
    'format' => '2',
    'name' => 'admin',
    'picture' => '',
    'data' => 'a:0:{}',
    'path' => 'content/guidance',
    'has_body' => '1',
    'comment_type' => '',
    'last_comment_timestamp' => '1305843625',
    'last_comment_name' => NULL,
    'comment_count' => '0',
    'taxonomy' => array(),
    'menu' => array(
      'link_title' => 'Guidance',
      'mlid' => 0,
      'plid' => '0',
      'menu_name' => 'secondary-links',
      'weight' => '1',
      'options' => array(),
      'module' => 'menu',
      'expanded' => '0',
      'hidden' => '0',
      'has_children' => '0',
      'customized' => 0,
      'parent_depth_limit' => 8,
    ),
    '#_export_node_encode_object' => '1',
  ),
)
